# TCL File Generated by Component Editor 13.1
# Sun Dec 23 20:07:29 CST 2018
# DO NOT MODIFY


# 
# can_controller "can_controller" v1.0
# warship 2018.12.23.20:07:29
# CAN bus controller Avalon interface
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module can_controller
# 
set_module_property DESCRIPTION "CAN bus controller Avalon interface"
set_module_property NAME can_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP MyIp
set_module_property AUTHOR warship
set_module_property DISPLAY_NAME can_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL can_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file can_controller.v VERILOG PATH HDL/can_controller.v TOP_LEVEL_FILE
add_fileset_file can_acf.v VERILOG PATH HDL/can_acf.v
add_fileset_file can_bsp.v VERILOG PATH HDL/can_bsp.v
add_fileset_file can_btl.v VERILOG PATH HDL/can_btl.v
add_fileset_file can_crc.v VERILOG PATH HDL/can_crc.v
add_fileset_file can_defines.v VERILOG PATH HDL/can_defines.v
add_fileset_file can_fifo.v VERILOG PATH HDL/can_fifo.v
add_fileset_file can_ibo.v VERILOG PATH HDL/can_ibo.v
add_fileset_file can_register.v VERILOG PATH HDL/can_register.v
add_fileset_file can_register_asyn.v VERILOG PATH HDL/can_register_asyn.v
add_fileset_file can_register_asyn_syn.v VERILOG PATH HDL/can_register_asyn_syn.v
add_fileset_file can_register_syn.v VERILOG PATH HDL/can_register_syn.v
add_fileset_file can_registers.v VERILOG PATH HDL/can_registers.v
add_fileset_file can_top.v VERILOG PATH HDL/can_top.v
add_fileset_file timescale.v VERILOG PATH HDL/timescale.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_address address Input 8
add_interface_port avalon_slave avs_chipselect chipselect Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_writedata writedata Input 8
add_interface_port avalon_slave avs_readdata readdata Output 8
add_interface_port avalon_slave avs_waitrequest_n waitrequest_n Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point can_clk_i
# 
add_interface can_clk_i clock end
set_interface_property can_clk_i clockRate 0
set_interface_property can_clk_i ENABLED true
set_interface_property can_clk_i EXPORT_OF ""
set_interface_property can_clk_i PORT_NAME_MAP ""
set_interface_property can_clk_i CMSIS_SVD_VARIABLES ""
set_interface_property can_clk_i SVD_ADDRESS_GROUP ""

add_interface_port can_clk_i can_clk clk Input 1


# 
# connection point can_rst
# 
add_interface can_rst reset end
set_interface_property can_rst associatedClock clock
set_interface_property can_rst synchronousEdges DEASSERT
set_interface_property can_rst ENABLED true
set_interface_property can_rst EXPORT_OF ""
set_interface_property can_rst PORT_NAME_MAP ""
set_interface_property can_rst CMSIS_SVD_VARIABLES ""
set_interface_property can_rst SVD_ADDRESS_GROUP ""

add_interface_port can_rst can_reset reset Input 1


# 
# connection point can_rt
# 
add_interface can_rt conduit end
set_interface_property can_rt associatedClock clock
set_interface_property can_rt associatedReset ""
set_interface_property can_rt ENABLED true
set_interface_property can_rt EXPORT_OF ""
set_interface_property can_rt PORT_NAME_MAP ""
set_interface_property can_rt CMSIS_SVD_VARIABLES ""
set_interface_property can_rt SVD_ADDRESS_GROUP ""

add_interface_port can_rt can_rx export Input 1
add_interface_port can_rt can_tx export Output 1


# 
# connection point can_irq_n
# 
add_interface can_irq_n interrupt end
set_interface_property can_irq_n associatedAddressablePoint avalon_slave
set_interface_property can_irq_n associatedClock clock
set_interface_property can_irq_n ENABLED true
set_interface_property can_irq_n EXPORT_OF ""
set_interface_property can_irq_n PORT_NAME_MAP ""
set_interface_property can_irq_n CMSIS_SVD_VARIABLES ""
set_interface_property can_irq_n SVD_ADDRESS_GROUP ""

add_interface_port can_irq_n can_irq_n irq_n Output 1


# 
# connection point can_clk_o
# 
add_interface can_clk_o clock start
set_interface_property can_clk_o associatedDirectClock ""
set_interface_property can_clk_o clockRate 0
set_interface_property can_clk_o clockRateKnown false
set_interface_property can_clk_o ENABLED true
set_interface_property can_clk_o EXPORT_OF ""
set_interface_property can_clk_o PORT_NAME_MAP ""
set_interface_property can_clk_o CMSIS_SVD_VARIABLES ""
set_interface_property can_clk_o SVD_ADDRESS_GROUP ""

add_interface_port can_clk_o can_clkout clk Output 1

