/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Chinese_WRYH32.c                                      *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      32                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 32                                            *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: F:\backup\ÏÔÊ¾µÄºº×Ö.txt                        *
* Range disabled: 0000 - FFFF                                        *
* Read pattern file: F:\backup\Fmicrosoftyahei.txt                   *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontChinese_WRYH32;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontChinese_WRYH32_539F[128] = { /* code 539F */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XX___,_____XX_,________,________,
  ___XX___,____XX__,________,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XX______,_____XX_,________,
  ___XX___,XX______,_____XX_,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XX______,_____XX_,________,
  ___XX___,XX______,_____XX_,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XXXXXXXX,XXXXXXX_,________,
  ___XX___,XX____XX,_____XX_,________,
  __XX____,__X___XX,__X_____,________,
  __XX____,_XXX__XX,__XXX___,________,
  __XX____,XXX___XX,____XX__,________,
  _XXX___X,XX____XX,_____XXX,________,
  _XX__XXX,X_____XX,______XX,X_______,
  XX____X_,__XXXXXX,_______X,________,
  _X______,__XXXXX_,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontChinese_WRYH32_5B50[128] = { /* code 5B50 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,__XXX___,________,
  ________,________,_XXX____,________,
  ________,_______X,XXX_____,________,
  ________,______XX,X_______,________,
  ________,_____XXX,________,________,
  ________,____XXX_,________,________,
  ________,____XX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ______XX,XXXXXX__,________,________,
  ______XX,XXXXX___,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontChinese_WRYH32_6B63[128] = { /* code 6B63 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XXXX,XXXXXXX_,________,
  ____XX__,____XXXX,XXXXXXX_,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  ____XX__,____XX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontChinese_WRYH32_70B9[128] = { /* code 70B9 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XXXXX,XXXXXXXX,________,
  ________,___XXXXX,XXXXXXXX,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XX___,________,____XX__,________,
  ___XX___,________,____XX__,________,
  ___XX___,________,____XX__,________,
  ___XX___,________,____XX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XX___,________,____XX__,________,
  ________,________,________,________,
  ___X___X,X_____X_,____X___,________,
  __XXX__X,XX___XXX,___XXX__,________,
  __XX____,XX____XX,____XX__,________,
  _XX_____,XX____XX,_____XX_,________,
  XXX_____,XXX____X,X____XXX,________,
  _X______,_X_____X,______X_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontChinese_WRYH32_CharInfo[4] = {
   {  25,  25,  4, acGUI_FontChinese_WRYH32_539F } /* code 539F */
  ,{  25,  25,  4, acGUI_FontChinese_WRYH32_5B50 } /* code 5B50 */
  ,{  25,  25,  4, acGUI_FontChinese_WRYH32_6B63 } /* code 6B63 */
  ,{  25,  25,  4, acGUI_FontChinese_WRYH32_70B9 } /* code 70B9 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontChinese_WRYH32_Prop4 = {
   0x70B9 /* first character */
  ,0x70B9 /* last character  */
  ,&GUI_FontChinese_WRYH32_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontChinese_WRYH32_Prop3 = {
   0x6B63 /* first character */
  ,0x6B63 /* last character  */
  ,&GUI_FontChinese_WRYH32_CharInfo[  2] /* address of first character */
  ,&GUI_FontChinese_WRYH32_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontChinese_WRYH32_Prop2 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontChinese_WRYH32_CharInfo[  1] /* address of first character */
  ,&GUI_FontChinese_WRYH32_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontChinese_WRYH32_Prop1 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_FontChinese_WRYH32_CharInfo[  0] /* address of first character */
  ,&GUI_FontChinese_WRYH32_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontChinese_WRYH32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,32 /* height of font  */
  ,32 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontChinese_WRYH32_Prop1}
  ,26 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,19 /* Height of capital characters */
};

